#windows::maven::maven_mirrors:
# - id: 'host'
#   url: 'http://10.0.2.2:8080/archiva/repository/all'
#   mirrorof: 'external:*'

#windows::chocolatey_webpi::offlineCache: 'C:\Downloads\webpicache'

# Required, to place settings in the correct place
windows::maven::user: 'Administrator'

# Required, for packages that install SQLExpress
windows::chocolatey_webpi::sqlPassword: 'abc123DEF!'

