#windows::maven::maven_mirrors:
# - id: 'host'
#   url: 'http://10.0.2.2:8080/archiva/repository/all'
#   mirrorof: 'external:*'

#windows::chocoloate_webpi::offline_cache: 'C:\Downloads\webpicache'

# Required, to place settings in the correct place
windows::maven::user: 'Administrator'

