# TODO: fold into original module
windows_java: {
  root_url: "http://download.oracle.com/otn-pub/java/jdk",
  7u60: {
    build_number: "7u60-b19",
    x64: {
      install_name: "Java SE Development Kit 7 Update 60 (64-bit)",
      install_path: "C:\\Program Files\\Java\\jdk1.7.0_60",
      jre_install_path: "C:\\Program Files\\Java\\jre7",
      file_name: "jdk-7u60-windows-x64.exe"
    }
  }
}

#maven_mirrors:
# - id: 'imac'
#   url: 'http://10.0.2.2:8080/archiva/repository/all'
#   mirrorof: 'external:*'

